### ISSUE TITLE
Websocket URL generated by the `app.js` is not checking trailing slash on the pathname

### ISSUE THREAD

**Issue by dduportal** [tsl0922/ttyd#100]
Hello!

Thanks for this piece of software, which is good a useful!

I am using ttyd behind Nginx (Kubernetes Ingress), with the default rewrite rule to provide it as a context:

* URL: http://HOSTNAME/devbox 
* Ingress (simplified) configuration:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: devbox
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: 1d
    nginx.ingress.kubernetes.io/proxy-send-timeout: 1d
    nginx.ingress.kubernetes.io/proxy-read-timeout: 1d
spec:
  rules:
  - host: 192.168.99.100.xip.io
    http:
      paths:
      - path: /devbox
        backend:
          serviceName: devbox
          servicePort: 7681
```

The HTML and javascript are correctly loaded thanks to the directives:
```
nginx.ingress.kubernetes.io/rewrite-target: "/"
nginx.ingress.kubernetes.io/add-base-url: "true"
```

But the websocket protocol tries to connect at the URL http://<HOSTNAME>/devboxws.

With my previous docker-compose configuration, I was doing a custom nginx rewrite, which was taking care of adding the trailing slash `/` to have http://HOSTNAME/devbox -> http://HOSTNAME/devbox/ 
but I would want to avoid this (performances and configuration pain).

My short-term solution is to replace on the fly and add the trailing slash with the nginx sub_filter module: 
```
nginx.ingress.kubernetes.io/configuration-snippet: |
      sub_filter_types application/javascript;
      sub_filter '"ws"' '"/ws"';
      sub_filter_once off;
```

I tracked down the code to this line: https://github.com/tsl0922/ttyd/blob/9715585fc1fb133137e7d3c6764d2dfa623fa321/html/js/app.js#L172  

Should we check the `window.location.pathname` for a trailing slash (and add it if absent) ?
Lik: 
```
url = (httpsEnabled ? 'wss://' : 'ws://') + window.location.host + window.location.pathname 
  + (window.location.pathnam.endsWith("/") ? "" : "/") + 'ws',
```

Alternatively, maybe the "base" tag could be used ? 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

Let me know if you want a PR?

Thanks in advance!
