### ISSUE TITLE
ttyd reconnection reset issue

### ISSUE THREAD

**Issue by fawazahmed0** [tsl0922/ttyd#1397]
**Describe the bug**
I use ttyd to compile package in remote pc. sometimes ttyd reconnects, causing the whole compilation to be killed.

**To Reproduce**
1. Create a github actions yml with following content and run it.
```yml
on: workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-24.04
    steps:
      - uses: fawazahmed0/action-debug@main
```
2. url to access terminal will be printed in github actions log. username and password is `admin`
3. execute consuming compilation process
4. After sometime(can take 1-2 hours) the ttyd reconnects, causing the whole compilation to get killed.

**Expected behavior**
On reconnection, it should continue and not kill the compilation

**Additional context**
[fawazahmed0/action-debug@main](https://github.com/fawazahmed0/action-debug) package uses ttyd & cloudflare tunnel
