### ISSUE TITLE
Custom background color?

### ISSUE THREAD

**Issue by BiatuAutMiahn** [tsl0922/ttyd#195]
Can you add an option to use a custom background color? imo black is better than grey.

**Comment by tsl0922** [comment]
```bash
ttyd -t 'theme={"background": "green"}' bash
```

Full theme keys: https://github.com/tsl0922/ttyd/blob/master/html/src/components/app.tsx#L17

**Comment by verhovsky** [comment]
@tsl0922 how do I change the selection color? I want to use a light theme (black text on white background), so I added this:

```yaml
theme:
    background: '#ffffff'
    foreground: '#2b2b2b'
    cursor: '#adadad'
```

but when I click and drag to highlight text it doesn't show my selection. I can still copy text, but I have to do it blind.

I tried `cursor: '#000000'` but that affects only the cursor, not the selection.
