### ISSUE TITLE
Access ttyd of host inside nginx-docker

### ISSUE THREAD

**Issue by collegeimprovements** [tsl0922/ttyd#315]
When we run ttyd from docker, we see docker's terminal in browser.
Is it possible to see host machine's terminal in browser when we run ttyd from docker?

Problem we are trying to solve: 

We are running `ttyd` on host machine and we want it on a web-url which can be configured only via nginx. This way we can make `host` server's bash prompt on web-url via nginx.

## `docker-compose.yml` file

```yaml
version: "2"
services:
  nginx:
    image: nginx:latest
    container_name: ttyd_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 9090:80
```

## `nginx.conf` file
```nginx
user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
  worker_connections  1024;
}

http {
  server {
    listen 80;
    server_name www.example.com example.com;

   location / {
      proxy_pass http://docker.for.mac.host.internal:4444;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
      proxy_set_header Host $host;
    }
  }
}
```
# But this gives WebSocket Error [Screenshot Attached]
![Screenshot 2020-04-18 at 9 19 30 PM](https://user-images.githubusercontent.com/1519705/79642293-5816a280-81ba-11ea-980e-f0491469e462.png)

How can we resolve that to make it interactive with the help of `ws` calls? 
What calls we need to cover in nginx.conf file.
