### ISSUE TITLE
allow changing the selection color

### ISSUE THREAD

**Issue by verhovsky** [tsl0922/ttyd#725]
**Is your feature request related to a problem? Please describe.**
I want to use a light theme (black text on white background), so I added this:

```yaml
theme:
    background: '#ffffff'
    foreground: '#2b2b2b'
    cursor: '#adadad'
```

but now when I highlight text to copy it, I can't see what I'm highlighting because the highlight becomes white on white.

**Describe the solution you'd like**

I would like to put this in my config:

```yaml
theme:
    selection: '#bbd6fc'
```
